include:
  - project: 'y_zokirjon/infrastructure'
    ref: 'main'      
    file: '/ci-templates/deployer-front-v1.yml'

  - project: 'y_zokirjon/infrastructure'
    ref: 'main'
    file: '/ci-templates/notifier.yml'

variables:
  DOCKER_IMAGE: "recruit_front"
  DOCKER_IMAGE_PROD: "front"

stages:
  - build
  - deploy
  - notify
  - cook
  - delivery

.ssh_setup:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    
deploy:
  stage: deploy
  extends: .deploy_watcher

prepare:
  stage: scan
  extends: .ssh_setup
  script:
    - echo "$ENV_PROD" > .env 
    - echo "🐳 Building $DOCKER_IMAGE:$TAG..."
    - docker build --build-arg TAG=$TAG -t $DOCKER_IMAGE:$TAG -f Dockerfile .

    - echo "🔍 Scanning Built Image with Host Trivy..."
    - trivy image --severity CRITICAL --exit-code 1 --no-progress $DOCKER_IMAGE:$TAG

    - echo "🚀 Security Check Passed. Streaming image to Production Server..."
    - docker save $DOCKER_IMAGE:$TAG | gzip | ssh -p $SERVER_PORT $EXTERNAL_SERVER "gunzip | docker load"
    
  allow_failure: true

delivery_to_prod:
  stage: delivery
  extends: .ssh_setup
  script:
    - |
        ssh -p $SERVER_PORT $EXTERNAL_SERVER "
        docker network create hr_net || true &&
        export DOCKER_IMAGE=$DOCKER_IMAGE &&
        export TAG=$TAG &&
        cd /srv/client &&
        sed -i \"s|image: .*front.*|image: $DOCKER_IMAGE:$TAG|g\" docker-compose.yml &&
        docker compose -f docker-compose.yml down --remove-orphans || true &&
        docker compose -f docker-compose.yml up -d "
        
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  tags:
    - temppriz
  environment:
    name: production
  needs: ["prepare"]


